[project]
name = "cost-janitor"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Anurag Gupta", email = "subscriptions@enerdatics.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.103",
    "mcp>=2.2.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
cost-janitor = "cost_janitor:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
